version : 2

models:
  - name: fraud_data_only
    description: data that is detected as fraud only
    columns:
      - name: isFraud
        description: data categorized by fraud, 1 for fraud and 0 for non-fraud
        tests:
          - accepted_values:
              values: [1,0]
    
  - name: fraud_data_filtered
    description: data that has been filtered
    columns:
      - name: amount
        description: total transaction by time
        tests:
          - not_null
